"""Normalizar catalogos de productos

Revision ID: 5c01ee1caa30
Revises: 
Create Date: 2026-07-16 04:37:20.931588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c01ee1caa30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mangas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('materiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tallas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipos_prenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('talla_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tallas', ['talla_id'], ['id'])
        batch_op.drop_column('talla')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_prenda_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('material_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('manga_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'tipos_prenda', ['tipo_prenda_id'], ['id'])
        batch_op.create_foreign_key(None, 'mangas', ['manga_id'], ['id'])
        batch_op.create_foreign_key(None, 'materiales', ['material_id'], ['id'])
        batch_op.drop_column('talla')
        batch_op.drop_column('stock_minimo')
        batch_op.drop_column('material')
        batch_op.drop_column('stock')
        batch_op.drop_column('manga')
        batch_op.drop_column('tipo_prenda')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_prenda', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('manga', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('stock', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('material', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('stock_minimo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('talla', mysql.VARCHAR(length=10), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('activo')
        batch_op.drop_column('manga_id')
        batch_op.drop_column('material_id')
        batch_op.drop_column('tipo_prenda_id')

    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('talla', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('talla_id')

    op.drop_table('tipos_prenda')
    op.drop_table('tallas')
    op.drop_table('materiales')
    op.drop_table('mangas')
    # ### end Alembic commands ###
